config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    registrations: 'registrations'
  }, skip: [:sessions]
  as :admin do
    get 'admin' => 'devise/sessions#new', as: :new_admin_session
    post 'admin' => 'devise/sessions#create', as: :admin_session
    delete 'logout' => 'devise/sessions#destroy', as: :destroy_admin_session
  end

  root 'pages#home'
  get 'about' => 'pages#about'
  get 'contact' => 'messages#new'
  post 'contact' => 'messages#create'
  get 'upload' => 'images#new', as: 'upload'
  get 'gallery' => 'images#index', as: 'gallery'
  get 'admin/:id' => 'admin#show', as: 'show_admin'
  resources :categories
  resources :images, except: %i[index new]
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :rememberable, and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :trackable, :validatable
  mount_uploader :profile_picture, ImageUploader
  has_many :images
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :images, dependent: :destroy
  validates :name, presence: true

  before_save :update_category_name

  private

  def update_category_name
    return unless name.present? || name.changed?

    self.name = name.capitalize
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :category
  mount_uploader :image, ImageUploader

  before_save :update_image_attributes
  validates_presence_of :image, :image_title, :image_description, :category_id

  private

  def update_image_attributes
    return unless new_record? || image_changed?

    self.image_file_size = image.file.size
    self.image_content_type = image.file.content_type
    self.landscape = true if image.is_landscape?(image)
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  validates_presence_of :name, :email, :message
  validates_format_of :email, with: Devise.email_regexp

  after_save :send_email_to_admin

  private

  def send_email_to_admin
    MessageMailer.new_message_notification(self).deliver_later
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_admin!

  def show; end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(_resource)
    gallery_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_admin!

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'New Category Created'
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = 'Category Updated'
      redirect_to categories_path
    else
      render 'edit'
    end
  end

  def index
    @categories = Category.all
  end

  def destroy
    @category = Category.find(params[:id]).destroy
    flash[:notice] = 'Category Deleted'
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :authenticate_admin!, except: [:index]

  def new
    @image = Image.new
  end

  def create
    @image = Image.new(image_params)
    if @image.save
      flash[:notice] = 'New Image Uploaded'
      redirect_to gallery_path
    else
      render 'new'
    end
  end

  def show
    @image = Image.find(params[:id])
  end

  def edit
    @image = Image.find(params[:id])
  end

  def update
    @image = Image.find(params[:id])
    if @image.update(image_params)
      flash[:notice] = 'Image Updated'
      redirect_to gallery_path
    else
      render 'edit'
    end
  end

  def index
    @images = Image.order('id DESC')
    @categories = Category.all
  end

  def destroy
    @image = Image.find(params[:id]).destroy
    flash[:notice] = 'Image Deleted'
    redirect_to gallery_path
  end

  private

  def image_params
    params.require(:image).permit(:image, :image_title, :image_description, :category_id, :front_page_image)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_image, only: [:new]

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      flash[:notice] = 'Thank you for your message. We will get back to you soon.'
      redirect_to contact_path
    else
      flash[:alert] = 'An error occurred while delivering this message.'
      render :new
    end
  end

  private

  def message_params
    params.require(:message).permit(:name, :email, :message)
  end

  def set_image
    images = Image.where(front_page_image: true, landscape: true)
    @contact_image = images.sample
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @images = Image.where(front_page_image: true).order('id DESC')
    render layout: 'home_layout'
  end

  def about
    @admin = Admin.first
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_action :check_admin_number, only: [:new]

  private

  def account_update_params
    params.require(:admin).permit(:profile_picture, :about, :email, :password, :password_confirmation,
                                  :current_password)
  end

  def check_admin_number
    admin_number = Admin.all.count
    return unless admin_number > 0

    redirect_to new_admin_session_path
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/admin/show.html.erb
<div class="section-w-image">
	<div class="row">
		<div class="col-md-4 contact-image" style="background: url(<%= current_admin.profile_picture %>) scroll center no-repeat;background-size: 100% 100%;"><p></p></div>
		<div class="col-md-8 col-md-offset-4 section-description dark">
			<h3>About Me</h3>
			<br>
			<h5>Traveller, recreational and technical diving instructor, cave diver and photographer.</h5>
			<br>
			<p><%= current_admin.about %></p>
			<div class="contact-info">
				<div class="info">
					<span class="social">
						<%= link_to 'https://web.facebook.com/Pawel-Ciechelski-Photography-1307521106035720/' do %><i class="fa fa-facebook-official"></i><% end %>
					</span>
				</div>
			</div><!-- / contact-info -->
		</div><!-- / section-description -->
	</div><!-- / row -->
</div><!-- / about-w-image-left -->
<!-- content -->
<%= link_to 'Edit Profile', edit_admin_registration_path, class: 'btn btn-primary-filled' %>
<%= javascript_include_tag 'jquery.easing.min', 'scrolling-nav', 'preloader', media: 'all', 'data-turbolinks-track' => true %>

app/views/categories/_form.html.erb
<% if @category.errors.any? %>
		<% @category.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"><%= msg %></div>
		<% end %>
	<% end %>
<%= form_for @category do |f| %>
	<div class="form-group">
		<%= f.label :name %>
		<%= f.text_field :name, class: 'form-control' %>
	</div>
	<br>
	<%= f.submit class: 'btn btn-md btn-primary-filled btn-form-submit' %>
	<%= link_to 'Back', categories_path, class: 'btn btn-md btn-primary-filled' %>
<% end %>

app/views/categories/edit.html.erb
<h4>Edit Category</h4>
<%= render 'form' %>
<%= javascript_include_tag 'jquery.easing.min', 'scrolling-nav', 'preloader', 'data-turbolinks-track' => true %>

app/views/categories/index.html.erb
<h2>Categories</h2>
<table class="table table-striped">
	<thead>
		<tr>
			<th>Category Name</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
		<% @categories.each do |cat| %>
		<tr>
			<td><%= cat.name %></td>
			<td>
				<%= link_to 'Edit', edit_category_path(cat), class: 'btn btn-xs btn-default' %>
				<%= link_to 'Delete', category_path(cat), method: :delete, data: { confirm: 'All images assosiated with this category will be deleted! Are you sure?' }, class: 'btn btn-xs btn-danger' %>
			</td>
		</tr>
		<% end %>
	</tbody>
</table>
<%= link_to 'Add Category', new_category_path, class: 'btn btn-md btn-primary-filled btn-form-submit' %>
<%= javascript_include_tag 'scrolling-nav', 'preloader', 'data-turbolinks-track' => true %>

app/views/categories/new.html.erb
<h4>Add new Category</h4>
<%= render 'form' %>
<%= javascript_include_tag 'scrolling-nav', 'preloader', 'data-turbolinks-track' => true %>

app/views/images/_form.html.erb
<%= form_for @image, html: { multipart: true } do |f| %>
	<% if @image.errors.any? %>
		<% @image.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"><%= msg %></div>
		<% end %>
	<% end %>
	<div class="form-group">
		<%= f.label :image %>
		<%= f.file_field :image %>
	</div>
	<br>
	<div class="form-group">
		<%= f.label :image_title %>
		<%= f.text_field :image_title, class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= f.label :category %>
		<%= f.select :category_id, Category.all.collect { |cat| [cat.name, cat.id] }, { include_blank: '- select one -' }, class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= f.label :image_description %>
		<%= f.text_area :image_description, class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= f.label :front_page_image %>
		<%= f.check_box :front_page_image %>
	</div>
	
	<%= f.submit class: 'btn btn-md btn-primary-filled btn-form-submit' %>
	<%= link_to 'Cancel', gallery_path, class: 'btn btn-md btn-primary-filled' %>
<% end %>

app/views/images/edit.html.erb
<h4>Update Image</h4>
<%= render 'form' %>
<%= javascript_include_tag 'scrolling-nav', 'preloader', 'data-turbolinks-track' => true %>

app/views/images/index.html.erb
<!-- projects -->
<section id="portfolio" class="no-gutter">
	<!-- portfolio filter -->
	<ul class="portfolio-filter list-inline text-center">
		<li><%= link_to 'All', '#', data: { group: "all" }, class: 'active' %></li>
		<% @categories.each do |cat| %>
			<li><%= link_to cat.name, '#', data: { group: "#{cat.id}" } %></li>
		<% end %>
	</ul><!--end portfolio filter -->
	<ul class="row portfolio list-unstyled gallery" id="grid">
		<% @images.each do |image| %>
			<!-- project -->
				<%= tag :li, class: ['col-xs-6', 'col-sm-3', 'project'], data: { groups: "[#{image.category.id}]" } %>
					<figure class="portfolio-item">
						<div class="hovereffect">  
							<%= link_to image.image.url, data: { lightbox: "all", title: "#{image.image_title}" } do %>
								<%= image_tag image.image.url(:thumb), class: 'img-responsive' %>                               
								<div class="overlay">
									<div class="hovereffect-title">
										<h5><%= image.image_title %></h5>
										<p><%= image.image_description %></p>
									</div>
								</div>
							<% end %>
						</div>
					</figure>
					<% if admin_signed_in? %>
						<%= link_to 'Edit', edit_image_path(image), class: 'btn btn-sm btn-default' %>
						<%= link_to 'Delete', image_path(image), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
					<% end %>
			</li>
			<!-- / project -->
		<% end %>
		<!-- sizer -->
		<li class="col-xs-6 col-sm-3 shuffle_sizer"></li>      
	</ul> <!-- / projects -->
</section>
<!-- / portfolio section 4col -->
<%= javascript_include_tag 'jquery.easing.min', 'preloader', 'jquery.shuffle.min', 'custom', media: 'all', 'data-turbolinks-track' => true %>

app/views/images/new.html.erb
<h4>Upload Image</h4>
<%= render 'form' %>
<%= javascript_include_tag 'scrolling-nav', 'preloader', 'data-turbolinks-track' => true %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="Underwater Photography">
		<meta name="keywords" content="underwater photography, photography, photo, picture, image, scuba diving, creative portfolio, responsive" />
		<meta name="author" content="Pawel Ciechelski">
		<title>Pawel Ciechelski Photography</title>
		<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
	</head>
	<body>
		<!-- preloader -->
		<div id="preloader">
			<div class="spinner spinner-round"></div>
		</div>
		<!-- / preloader -->
		<%= render 'partials/header' %>
		<!-- content -->
		<div id="page-content" class="container-fluid has-fixed-top">
			<%= content_tag(:div, flash[:error], class: 'alert alert-danger' ) if flash[:error] %>
			<%= content_tag(:div, flash[:notice], class: 'alert alert-success') if flash[:notice] %>
			<%= content_tag(:div, flash[:alert], class: 'alert alert-danger') if flash[:alert] %>
			<%= yield %>
		</div>
		<!-- / page-content -->
		<%= render 'partials/footer' %>
	</body>
</html>

app/views/layouts/home_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Underwater Photography">
    <meta name="keywords" content="underwater photography, photography, photo, picture, image, scuba diving, creative portfolio, responsive" />
    <meta name="author" content="Pawel Ciechelski">
    <link rel="icon" href="public/favicon.png">
    <title>Pawel Ciechelski Photography</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <!-- preloader -->
    <div id="preloader">
        <div class="spinner spinner-round"></div>
    </div>
    <!-- / preloader -->
    <%= render 'partials/header' %>
    <%= content_tag(:div, flash[:notice], class: 'hidden') if flash[:notice] %>
    <!-- content -->
    <%= yield %>
    <!-- / page-content -->
    <%= render 'partials/footer' %>
  </body>
</html>

app/views/messages/new.html.erb
<div class="section-w-image">
	<div class="row">
		<div class="col-md-5 contact-image" style="background: url(<%= @contact_image.image if @contact_image != nil %>) scroll center no-repeat;background-size: 100% 100%;"><p></p></div>
		<div class="col-md-7 col-md-offset-5 section-description dark">
			<div class="page-header text-left">
					<h2>Get in Touch</h2>
			</div><!-- / page-header -->
			<br>
			<p>If you are interested in cooperation, if you need a specific shot taken just for you or if you would like to buy one of my photos please do not hesitate to contact me by filling out the form below or catch me on facebook.</p>
			<div class="contact-info">
				<div class="info">
					<span class="social">
						<%= link_to 'https://web.facebook.com/Pawel-Ciechelski-Photography-1307521106035720/' do %><i class="fa fa-facebook-official fa-lg"></i><% end %>
					</span>
				</div>
			</div><!-- / contact-info -->
		</div><!-- / section-description -->
	</div><!-- / row -->
</div><!-- / contact-w-image-left -->

<div class="row contact-area">
	<div class="col-sm-8 col-sm-offset-2 contact-form-area">
		<!-- contact form 1col -->
		<div id="contact-form-1">
			<%= form_for @message, url: contact_path, id: 'contactForm', data: { toggle: 'validator' } do |f| %>
				<div class="form-group">
					<%= f.text_field :name, placeholder: "Name", class: 'form-control', required: true %>
					<div class="help-block with-errors"></div>
				</div>	
				<div class="form-group">
					<%= f.email_field :email, placeholder: "Email", class: 'form-control', required: true %>
					<div class="help-block with-errors"></div>
				</div>	
				<div class="form-group">
					<%= f.text_area :message, placeholder: "Message", class: 'form-control', rows: '5', required: true %>
					<div class="help-block with-errors"></div>
				</div>
				<%= f.submit "Send Message", id: 'form-submit', class: 'btn btn-md btn-primary-filled btn-form-submit' %>
				<div id='msgSubmit' class="h3 text-center hidden"></div>
				<div class="clearfix"></div>
			<% end %>
		</div><!-- / contact form 1col -->
	</div><!-- / col-sm-6 -->
</div><!-- / contact-area -->
<%= javascript_include_tag 'jquery.easing.min', 'scrolling-nav', 'preloader', media: 'all', 'data-turbolinks-track' => true %>

app/views/pages/about.html.erb
<!-- content -->
<div class="section-w-image">
	<div class="row">
		<div class="col-md-4 contact-image" style="background: url(<%= @admin.profile_picture if @admin %>) scroll center no-repeat;background-size: 100% 100%;"><p></p></div>
		<div class="col-md-8 col-md-offset-4 section-description dark">
			<h3>About Me</h3>
			<br>
			<h5>Traveller, recreational and technical diving instructor, cave diver and photographer.</h5>
			<br>
			<p><%= @admin.about if @admin %></p>
			<div class="contact-info">
				<div class="info">
					<span class="social">
						<%= link_to 'https://web.facebook.com/Pawel-Ciechelski-Photography-1307521106035720/' do %><i class="fa fa-facebook-official"></i><% end %>
					</span>
				</div>
			</div><!-- / contact-info -->
		</div><!-- / section-description -->
	</div><!-- / row -->
</div><!-- / about-w-image-left -->
<!-- content -->
<%= javascript_include_tag 'jquery.easing.min', 'scrolling-nav', 'preloader', media: 'all', 'data-turbolinks-track' => true %>

app/views/pages/home.html.erb
<!-- content -->
<div class="full-height">
	<div class="full-height-wrapper">
		<div class="slider-container">
			<div class="slider-wrapper">
				<div class="slider variable-width">
					<% @images.each do |image| %>
						<div><%= image_tag image.image %></div>
					<% end %>
				</div>
			</div><!-- / slider-wrapper -->
		</div><!-- / slider-container -->
	</div><!-- / full-height-wrapper -->
</div><!-- / full-height -->
<!-- / content -->
<%= javascript_include_tag 'preloader', 'slick', media: 'all', 'data-turbolinks-track' => true %>
<!-- sliders -->
<script type="text/javascript">
$('.variable-width').slick({
  dots: false,
  infinite: true,
  speed: 300,
  slidesToShow: 1,
  centerMode: true,
  useTransform: true,
  draggable: true,
  swipe: true,
  variableWidth: true,
  adaptiveHeight: true,
  speed: 700,
  cssEase: 'linear'
});
</script>
<!-- / sliders -->

app/views/partials/_footer.html.erb
<!-- footer -->
<footer class="light-footer fixed-bottom">
	<div class="container-fluid">
		<p class="footer-info">© 2017 - <strong>PawelCiechelski</strong> - Photography. All Rights Reserved.
			<span class="social pull-right">
				<%= link_to 'https://web.facebook.com/Pawel-Ciechelski-Photography-1307521106035720/' do %><i class="fa fa-facebook-official fa-lg"></i><% end %>
			</span>
		</p>
	</div><!-- / container -->
</footer>
<!-- / footer -->

app/views/partials/_header.html.erb
<!-- header -->
<header>
  <nav class="navbar-1 navbar navbar-default fixed-top">
    <div class="container-fluid navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: 'navbar-brand' do %>PAWEL CIECHELSKI <small>PHOTOGRAPHY</small><% end %>
      <%= link_to root_path, class: 'sm-navbar-brand' do %>PCP<% end %>
    </div><!-- / navbar-header -->
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
      <% if admin_signed_in? %>
        <li <% if [params[:controller], params[:action]]  == ['pages', 'home'] %>class='active'<% end %>><%= link_to root_path do %><span>Home</span><% end %></li>                 
        <li <% if [params[:controller], params[:action]]  == ['images', 'index'] %>class='active'<% end %>><%= link_to gallery_path do %><span>Gallery</span><% end %></li>
        <li <% if [params[:controller], params[:action]]  == ['images', 'new'] %>class='active'<% end %>><%= link_to upload_path do %><span>Add Image</span><% end %></li>
        <li <% if [params[:controller], params[:action]]  == ['categories', 'index'] %>class='active'<% end %>><%= link_to categories_path do %><span>Categories</span><% end %></li>
        <li <% if [params[:controller], params[:action]]  == ['admin', 'show'] %>class='active'<% end %>><%= link_to show_admin_path(current_admin.id) do %><span>My Account</span><% end %></li>
        <li><%= link_to destroy_admin_session_path, method: :delete do %><span>Sign Out</span><% end %></li>
      <% else %>
        <li <% if [params[:controller], params[:action]]  == ['pages', 'home'] %>class='active'<% end %>><%= link_to root_path do %><span>Home</span><% end %></li>
        <li <% if [params[:controller], params[:action]]  == ['pages', 'about'] %>class='active'<% end %>><%= link_to about_path do %><span>About Me</span><% end %></li> 
        <li <% if [params[:controller], params[:action]]  == ['images', 'index'] %>class='active'<% end %>><%= link_to gallery_path do %><span>Gallery</span><% end %></li>
        <li <% if [params[:controller], params[:action]]  == ['messages', 'new'] %>class='active'<% end %>><%= link_to contact_path do %><span>Contact</span><% end %></li>
      <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </nav>
</header>
<!-- / header -->